name: SSU
favicon: null
layout_spectrum: 0
typography_spectrum: 0.73875
title: Scholarship Sports USA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ee2527'
    - '#435eab'
    - '#000000'
    - '#00ffff'
  brandStrength: 0.125
  lightness: 0.0625
  saturation: 1
  rhythmicContrast: 0
purpose: []
